# Generated by Django 2.2.1 on 2019-06-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190618_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='url',
            new_name='link',
        ),
    ]
