# Generated by Django 2.2.1 on 2019-06-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190621_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='icon',
            new_name='icon_image',
        ),
    ]
